// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.20.3
// source: gaocachepb/gaocache.proto

package gaocachepb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// GaocacheClient is the client API for Gaocache service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GaocacheClient interface {
	// Get方法，这里采用普通rpc
	Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error)
}

type gaocacheClient struct {
	cc grpc.ClientConnInterface
}

func NewGaocacheClient(cc grpc.ClientConnInterface) GaocacheClient {
	return &gaocacheClient{cc}
}

func (c *gaocacheClient) Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error) {
	out := new(GetResponse)
	err := c.cc.Invoke(ctx, "/gaocachepb.Gaocache/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GaocacheServer is the server API for Gaocache service.
// All implementations must embed UnimplementedGaocacheServer
// for forward compatibility
type GaocacheServer interface {
	// Get方法，这里采用普通rpc
	Get(context.Context, *GetRequest) (*GetResponse, error)
	mustEmbedUnimplementedGaocacheServer()
}

// UnimplementedGaocacheServer must be embedded to have forward compatible implementations.
type UnimplementedGaocacheServer struct {
}

func (UnimplementedGaocacheServer) Get(context.Context, *GetRequest) (*GetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedGaocacheServer) mustEmbedUnimplementedGaocacheServer() {}

// UnsafeGaocacheServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GaocacheServer will
// result in compilation errors.
type UnsafeGaocacheServer interface {
	mustEmbedUnimplementedGaocacheServer()
}

func RegisterGaocacheServer(s grpc.ServiceRegistrar, srv GaocacheServer) {
	s.RegisterService(&Gaocache_ServiceDesc, srv)
}

func _Gaocache_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GaocacheServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gaocachepb.Gaocache/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GaocacheServer).Get(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Gaocache_ServiceDesc is the grpc.ServiceDesc for Gaocache service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Gaocache_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gaocachepb.Gaocache",
	HandlerType: (*GaocacheServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _Gaocache_Get_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "gaocachepb/gaocache.proto",
}
